### ISSUE TITLE
Test file issue

### ISSUE THREAD

**Issue by lahorkarim** [tqxli/breast_ultrasound_lesion_segmentation_PyTorch#2]
Thanks for sharing this amazing project!
I have trained ResUnet on BUSI dataset (2D) and it worked well. However, there is an issue with the test file because it requires 3d images. Would you take a look at it?

Also, one suggestion, why don't you split the BUSI dataset to train and test or use k-fold validation since the dataset is small?

**Comment by tqxli** [comment]
Hi! If you look into the function `segment_3d_input`, you might notice that the arg `path_to_image` is a directory containing a set of 2D images - I was working on some private video-like data which were unpacked into 2D images. So for the inference, I would suggest using `segment_3d_input` still, but make `path_to_image` be some directory containing the images you'd like to get predictions, or make some slight changes to predict on your test set. 

I agree that having k-fold would be nice; I actually did it with some other datasets but not having the codes for BUSI in this repository.
